# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy App
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        script: |
          rm -r build
          rm -r /srv/dist
          mkdir build
          cd build
          git clone -b production git@github.com:phil-burney/Autafi.git
          cd Autafi/front-end
          mv dist /srv
          echo "Deployment to digitalocean successful"
          rm /srv/server/index.js
          rm -r /srv/server/models
          mv 

          
          
          
